### ISSUE TITLE
bump_version?

### ISSUE THREAD

**Issue by iSplasher** [aarhusstadsarkiv/stadsarkiv-client#127]
Bare et spørgsmål, men hvad er det for et værktøj der bruger `tool.bump_version` i pyproject filen? Det lyder brugbart :) og jeg vil gerne integrere det i webservice også.

**Comment by diversen7** [comment]
Det er et lille "tool" jeg har lavet. Du kan finde det her: https://github.com/diversen/bump-py-version Du er velkommen til at foreslå forbedringer - da det er relativt enkelt indtil nu :)
