### ISSUE TITLE
Add documentation to the default client

### ISSUE THREAD

**Issue by clausjuhl** [aarhusstadsarkiv/stadsarkiv-client#216]
We should integrate the documentation for `stadsarkiv-client` into the default frontend: client.openaws.dk. It should be accessable via the menu with its own menu-header.

- Log ind
- Ny Bruger
- Dokumentation
  - CLI-værktøjet
  - Konfigurationsmuligheder
  - Settings
  - Deployment
  - ...

**Comment by diversen7** [comment]
This is live on client.openaws.dk I just added the documentation menu as a sub menu on the documentation pages. And not in the main menu.
