### ISSUE TITLE
user settings should be in yaml, toml or similar format

### ISSUE THREAD

**Issue by clausjuhl** [aarhusstadsarkiv/stadsarkiv-client#260]
I think it would be better to require that the user settings file should be in yaml, toml or similar format thas is generally used for configuration files whether the source code is python, php, rust...

**Comment by diversen7** [comment]
Hej Claus, du kan se `yaml` settings format som det er netop nu: https://github.com/aarhusstadsarkiv/stadsarkiv-client/blob/main/example-config-simple/settings.yml Det kan være du har forslag til forbedringer.
